# Bag Of Words using SKLEARN

In [63]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [64]:
corpus = [
     'this coffee is very bad and is expensive',
     'this coffee is not bad and is cheap',
     'this coffee is not amazing and is not affordable',
]

In [66]:
vectorizer=CountVectorizer()
vectorizer.fit(corpus)
print('Vocabulary: ',vectorizer.vocabulary_)

Vocabulary:  {'this': 9, 'coffee': 5, 'is': 7, 'very': 10, 'bad': 3, 'and': 2, 'expensive': 6, 'not': 8, 'cheap': 4, 'amazing': 1, 'affordable': 0}


In [67]:
vector=vectorizer.transform(corpus)
print(vector.toarray())

[[0 0 1 1 0 1 1 2 0 1 1]
 [0 0 1 1 1 1 0 2 1 1 0]
 [1 1 1 0 0 1 0 2 2 1 0]]
